### ISSUE TITLE
Написать класс активности для отображения информации о конкретном лекарственном средстве

### ISSUE THREAD

**Issue by DarkLab** [khasang-incubator/Android_2016_05_03#16]

**Comment by grolegor** [comment]
В активити будет передаватья либо экземпляр класса Drug либо его id. В первом случае просто вызываем необходимые методы у инстанса для получения информации о препарате. Во втором случае создаем инстанс - new Drug(id) с этим айди и опять перебираем необходимые методы для получения информации о препарате.
В обоих случаях перед этим следует инициализировать БД (пока что нет единого места где мы это делаем), метод - PillsDBHelper.init(Context c) в него передаем контекст - подойдет this
