### ISSUE TITLE
Разработка структуры БД

### ISSUE THREAD

**Issue by DarkLab** [khasang-incubator/Android_2016_05_03#6]
Разработать структуру БД для хранения информации, учитывая текущий и последующие версии приложения (на основе User Stories и Road Map)

**Comment by grolegor** [comment]
![db_structure](https://cloud.githubusercontent.com/assets/17448507/15117905/6f0dcde6-1612-11e6-9e9d-99751fc140c7.png)

**Comment by grolegor** [comment]
![db_structure2](https://cloud.githubusercontent.com/assets/17448507/15121038/3230d67a-1621-11e6-8ae3-be8672542995.png)

**Comment by grolegor** [comment]
Решили использовать первый вариант
