### ISSUE TITLE
Нарисовать иконку (логотип) приложения

### ISSUE THREAD

**Issue by DarkLab** [khasang-incubator/Android_2016_05_03#8]

**Comment by Wheatgrh** [comment]
![pills_helper_v2 material](https://cloud.githubusercontent.com/assets/14089214/15118979/1657353c-1628-11e6-920a-4f69d1452f7b.jpg)
![pills_helper_v2 1](https://cloud.githubusercontent.com/assets/14089214/15118980/165819e8-1628-11e6-9c32-c105afdd87cd.jpg)
