### ISSUE TITLE
Реализация работы с БД

### ISSUE THREAD

**Issue by grolegor** [khasang-incubator/Android_2016_05_03#9]
Создать класс-helper, который будет создавать пустую БД, наполнение, апгрейд и т.п., предоставлять интерфейс взаимодействия с нашей базой данных (инкапсулировать внутри sql-запросы, чтобы пользователи этого класса вызывали только необходимые методы)

**Comment by DarkLab** [comment]
http://developer.android.com/intl/ru/training/basics/data-storage/databases.html

**Comment by grolegor** [comment]
Инструкция для подключения внешней базы (работает пока что только для ветки Feature/UseExistDB)
1. Скачиваем архив
2. Создаем assets (правой кнопкой по app -> new -> folder -> assets folder)
3. target source set = main
4. в assets создаем подпапку databases
5. Ложим раскапованный файл pills.db
Всё.
Для тестирования можно прописать в MainActivity в onCreate() строчку (PillsDBHelper.getInstance(this)).getReadableDatabase();
После этого запускаем приложение.
В логах мы увидим что-то типо такого:
05-14 17:19:31.337 26083-26083/com.khasang.pillshelper W/SQLiteAssetHelper: copying database from assets...
05-14 17:19:34.610 26083-26083/com.khasang.pillshelper W/SQLiteAssetHelper: database copy complete
05-14 17:19:34.614 26083-26083/com.khasang.pillshelper I/SQLiteAssetHelper: successfully opened database pills.db

**Comment by grolegor** [comment]
для добавления новой функциональности, требуемой от хелпера будем создавать отдельные ишью. основные методы для поиска и получения информации о лекарстве реализованы.
